### ISSUE TITLE
Generated code needs to be ignored

### ISSUE THREAD

**Issue by amccool** [bstauff/FindStatics#5] opened 2017-05-02 00:18 UTC
generated code such as this, needs to check its attribute and ignore it

probably start with if the class has a `global::System.CodeDom.Compiler.GeneratedCodeAttribute`

`    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.4.0.0"), global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute, global::Orleans.CodeGeneration.SerializerAttribute(typeof (global::Rb.Nci.Actor.SipGrainInterfaces.StaffPhoneOrServiceLevel))]
    internal class OrleansCodeGenRb_Nci_Actor_SipGrainInterfaces_StaffPhoneOrServiceLevelSerializer
    {
        private static readonly global::System.Reflection.FieldInfo field4 = typeof (global::Rb.Nci.Actor.SipGrainInterfaces.StaffPhoneOrServiceLevel).@GetTypeInfo().@GetField("<CoverStaffPhone>k__BackingField", (System.@Reflection.@BindingFlags.@Instance | System.@Reflection.@BindingFlags.@NonPublic | System.@Reflection.@BindingFlags.@Public));
        private static readonly global::System.Action<global::Rb.Nci.Actor.SipGrainInterfaces.StaffPhoneOrServiceLevel, global::System.Collections.Generic.List<global::System.Guid>> setField4 = (global::System.Action<global::Rb.Nci.Actor.SipGrainInterfaces.StaffPhoneOrServiceLevel, global::System.Collections.Generic.List<global::System.Guid>>)global::Orleans.Serialization.SerializationManager.@GetReferenceSetter(field4);
        [global::Orleans.CodeGeneration.CopierMethodAttribute]
        public static global::System.Object DeepCopier(global::System.Object original, global::Orleans.Serialization.ICopyContext context)
        {
            global::Rb.Nci.Actor.SipGrainInterfaces.StaffPhoneOrServiceLevel input = ((global::Rb.Nci.Actor.SipGrainInterfaces.StaffPhoneOrServiceLevel)original);
            global::Rb.Nci.Actor.SipGrainInterfaces.StaffPhoneOrServiceLevel result = (global::Rb.Nci.Actor.SipGrainInterfaces.StaffPhoneOrServiceLevel)global::System.Runtime.Serialization.FormatterServices.@GetUninitializedObject(typeof (global::Rb.Nci.Actor.SipGrainInterfaces.StaffPhoneOrServiceLevel));
            context.@RecordCopy(original, result);
            result.@BrcMessageSequenceNumber = input.@BrcMessageSequenceNumber;
            result.@BrcMessageSessionNumber = input.@BrcMessageSessionNumber;
            setField4(result, (global::System.Collections.Generic.List<global::System.Guid>)global::Orleans.Serialization.SerializationManager.@DeepCopyInner(input.@CoverStaffPhone, context));
            result.@PhoneName = input.@PhoneName;
            result.@ServiceLevel = input.@ServiceLevel;
            result.@Tag = input.@Tag;
            return result;
        }
`

**Comment by bstauff** [comment] 2017-05-03 13:48
Duplicate of #6

**Closed as completed by bstauff** 2017-05-03 13:48 UTC
